---
- name: Recursively remove directory
  file:
    path: /opt/tomcat/webapps/Helloworldwebapp-dev.war
    state: absent

- name: copy file
  copy:
    src: '/home/centos/jenkins/workspace/devops1/Helloworldwebapp-dev.war'
    dest: '/opt/tomcat/webapps'

- name: start tomcat
  become: yes
  command: '/bin/sh /opt/tomcat/bin/startup.sh' 

 


